"""Make is_active non-nullable

Revision ID: 06a5a837b53e
Revises: e6389d678a7d
Create Date: 2025-07-04 13:26:21.370684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06a5a837b53e'
down_revision: Union[str, Sequence[str], None] = 'e6389d678a7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # First, update any NULL values to TRUE
    op.execute("UPDATE profiles SET is_active = TRUE WHERE is_active IS NULL")
    
    # Then make the column non-nullable
    op.alter_column('profiles', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
