"""Create applications table

Revision ID: b29da5819aa5
Revises: 5bdb7ce9aaa3
Create Date: 2025-07-27 00:23:22.677877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b29da5819aa5'
down_revision: Union[str, Sequence[str], None] = '5bdb7ce9aaa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.alter_column('applications', 'document_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('applications_user_id_requested_role_id_key'), 'applications', type_='unique')
    op.drop_constraint(op.f('applications_user_id_fkey'), 'applications', type_='foreignkey')
    op.create_foreign_key(None, 'applications', 'profiles', ['user_id'], ['id'])
    op.alter_column('profiles', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('profiles', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('profiles', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.create_foreign_key(op.f('applications_user_id_fkey'), 'applications', 'profiles', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('applications_user_id_requested_role_id_key'), 'applications', ['user_id', 'requested_role_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('applications', 'document_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('applications', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    # ### end Alembic commands ###
