"""add_wallet_balance_to_profiles

Revision ID: cf3546707766
Revises: 6029a00570d4
Create Date: 2025-07-27 20:25:16.416179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf3546707766'
down_revision: Union[str, Sequence[str], None] = '6029a00570d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('wallet_balance', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'wallet_balance')
    # ### end Alembic commands ###
